# Generated by Django 4.0.4 on 2022-06-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.CharField(max_length=50),
        ),
    ]
