# Generated by Django 4.0.4 on 2022-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_alter_libros_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='link_editorial',
            field=models.CharField(default='link', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libros',
            name='editorial',
            field=models.CharField(default='editorial', max_length=50),
            preserve_default=False,
        ),
    ]
