# Generated by Django 4.0.4 on 2022-06-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0003_editorial_link_editorial_libros_editorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='nombre',
            new_name='name',
        ),
    ]
