# Generated by Django 4.0.4 on 2022-06-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_rename_nombre_libros_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
