# Generated by Django 4.0.4 on 2022-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0006_editorial_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='foto',
            field=models.ImageField(upload_to='imgs/'),
        ),
    ]
