# Generated by Django 4.0.4 on 2022-06-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0007_alter_editorial_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.editorial'),
        ),
    ]
