# Generated by Django 4.0.4 on 2022-06-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0010_libros_editorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='editorial',
        ),
    ]
