# Generated by Django 4.0.4 on 2022-07-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0012_libros_editorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='libros',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='locales',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locales'},
        ),
    ]
